name: "Purge Cloudflare Cache"
description: "This action will purge the cache of the cloudflare cdn"
author: "samcrosoft@gmail.com"

inputs:
  Cloudflare_Api:
    description: "The API key that has permission for clearning the cache"
    required: true

outputs:
  random_out:
    description: This is a random value returned
    value: ${{steps.call_ip_info.outputs.random_number}}
runs: 
  using: "composite"
  steps:
    - shell: bash
      id: call_ip_info
      run: |
        echo Clear the cache With key ${{ inputs.Cloudflare_Api }}.
        # get the calling IP
        curl -s ipinfo.io/json 
        echo "random_number=${RANDOM}" >> $GITHUB_OUTPUT