name: Compilation Workflow
on: push
env:
  GLOBAL_AGENT_NAME: Compilation-Ubuntu

jobs:
  setup_deps:
    runs-on: ubuntu-latest
    env:
      AGENT_NAME: Compilation-Image
    steps:
      - name: my-step
        run: |
          echo "Hello World!";
          echo "the job env variable is ${AGENT_NAME}"
          echo "the workflow env variable is ${GLOBAL_AGENT_NAME}"

  compile:
    runs-on: ubuntu-latest
    needs:
      - setup_deps
    steps:
      - name: Build Artefact
        run: |
          whoami
          echo ${PWD}